# Generated by Django 4.0.2 on 2022-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
